/*

001 | 금융회사 | 1
002 | 금융 유관기관 | 2
003 | 일반기업고객 | 3
004 | 개인고객 | 4
005 | 기타 | 5

*/

insert into TC_CMMNCODE_DETAIL (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID, UPPER_CODE, DEPTH, SORT_ORDR) values ('금융회사','금융회사','Y','001','COM120',NOW(),'test',NOW(),'test',0,1,1);
insert into TC_CMMNCODE_DETAIL (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID, UPPER_CODE, DEPTH, SORT_ORDR) values ('금융 유관기관','금융 유관기관','Y','002','COM120',NOW(),'test',NOW(),'test',0,1,2);
insert into TC_CMMNCODE_DETAIL (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID, UPPER_CODE, DEPTH, SORT_ORDR) values ('일반기업고객','일반기업고객','Y','003','COM120',NOW(),'test',NOW(),'test',0,1,3);
insert into TC_CMMNCODE_DETAIL (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID, UPPER_CODE, DEPTH, SORT_ORDR) values ('개인고객','개인고객','Y','004','COM120',NOW(),'test',NOW(),'test',0,1,4);
insert into TC_CMMNCODE_DETAIL (CODE_NM, CODE_DC, USE_AT, CODE, CODE_ID, FRST_REGIST_PNTTM, FRST_REGISTER_ID, LAST_UPDT_PNTTM, LAST_UPDUSR_ID, UPPER_CODE, DEPTH, SORT_ORDR) values ('기타','기타','Y','005','COM120',NOW(),'test',NOW(),'test',0,1,5);

